spring.application.name=unsichere_web-app

# database configuration
spring.datasource.url=jdbc:h2:file:./data/unsicheredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL configuration
spring.sql.init.mode=always